<?php
/**
 * Created by PhpStorm.
 * User: William
 * Date: 8/6/2016
 * Time: 12:46 PM
 */

define('LANGUAGE_DEFAULT','DE');
define('LANGUAGE_DE','DE');
define('LANGUAGE_EN','EN');
define('LANGUAGE_ID','ID');

define('BOOKS_VIEW_LIMIT_DEFAULT',10);
define('BOOKS_VIEW_LIMIT_LATEST',4);
define('BOOKS_VIEW_LIMIT_RECOMENDED',6);

define('BOOK_STATUS_NOT_AVAILABLE','NOT_AVAILABLE');
define('BOOK_STATUS_PENDING_ADMIN_APPROVAL','PENDING_ADMIN_APPROVAL');
define('BOOK_STATUS_RESERVED','RESERVED');
define('BOOK_STATUS_BORROWED','BORROWED');
define('BOOK_STATUS_AVAILABLE','AVAILABLE');

define('LOAN_STATUS_REQUESTED','REQUESTED');
define('LOAN_STATUS_BORROWED','BORROWED');
define('LOAN_STATUS_CANCELED','CANCELED');
define('LOAN_STATUS_REJECTED','REJECTED');
define('LOAN_STATUS_RETURNED','RETURNED');
